### ISSUE TITLE
ossindex.sonatype.org - no trace to host

### ISSUE THREAD

**Issue by aeneasr** [sonatype-nexus-community/nancy#203]
All CI pipelines and local executions fail with:

```
% traceroute ossindex.sonatype.org 
traceroute: unknown host ossindex.sonatype.org
```

cc @bhamail / @DarthHater

**Comment by bhamail** [comment]
@aeneasr It sounds like your network might be blocking connections to ossindex. `nancy` needs to connect to ossindex in order to check for vulnerabilities. Can you ping ossindex from the machine running the CI build? e.g. What does the following curl command show when run on your CI build machine?:

```
$ curl https://ossindex.sonatype.org/api/v3/component-report
{"code":405,"message":"HTTP 405 Method Not Allowed"}
```

If that doesn't shed light, could you provide more information, and the full error you're seeing?

**Comment by aeneasr** [comment]
Looks like it was just a hick-up - the trace failed in both CI (I guess AWS?) and locally (my home) which is why I opened this issue first! Anyway, thank you for the quick response!
