### ISSUE TITLE
Configurable cache directory

### ISSUE THREAD

**Issue by calvinbui** [sonatype-nexus-community/nancy#216]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Set a unique cache directory

* **What feature or behavior is this required for?**
Caching results between runs

* **How could we solve this issue? (Not knowing is okay!)**
I believe this will need some changes: https://github.com/sonatype-nexus-community/go-sona-types/blob/a618cf1b0a4b00832ff05cd83f16114d5bc43c48/ossindex/internal/cache/cache.go#L67

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by bhamail** [comment]
Thanks for creating this issue. Could you elaborate on your use case for this? I'm just trying to understand the details.

**Comment by calvinbui** [comment]
Speeding up CI builds

**Comment by ihavespoons** [comment]
Putting a plus 1 on this issue. I am trying to run this out of a Lambda function and the dependent library https://github.com/sonatype-nexus-community/go-sona-types/ causes a critical error because its using usr.HomeDir to determine home directory. Unfortunately this relies on /etc/passwd and ignores the $HOME variable. This means this software is essentially impossible to run in a Serverless environment.

**Comment by DarthHater** [comment]
@calvinbui @ihavespoons I'll see if I can jet this through today!
