### ISSUE TITLE
nancy requires glibc

### ISSUE THREAD

**Issue by s-spindler** [sonatype-nexus-community/nancy#32]
I'm trying to run nancy as part of my build chain which uses an alpine tag (`1.13.0-alpine3.10`) of the [official golang docker image](https://hub.docker.com/_/golang).

The nancy binary would not run. To reproduce, create the following Dockerfile:

```
FROM golang:1.13.0-alpine3.10

RUN wget -O- -q "https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.24/nancy-linux.amd64-v0.0.24" > /usr/bin/nancy\
    && chmod +x /usr/bin/nancy
```

And build & run it like this: `docker run -it --rm $(docker build -q .) /usr/bin/nancy `

The result will be `standard_init_linux.go:211: exec user process caused "no such file or directory"`.

This is due to nancy being built with `CGO_ENABLED=1` (the default setting) against glibc. Since alpine does not bring a glibc but musl as their libc implementation this doesn't work.

As far as I can see nancy does not need `CGO_ENABLED` so the fix is simple: disable it. I will open a PR...

/cc @bhamail / @DarthHater

**Comment by s-spindler** [comment]
@bhamail @DarthHater Looks like this issue is back since version 0.0.34. It can be reproduced as originally reported. Dockerfile:
```
FROM golang:1.13.0-alpine3.10

RUN wget -O- -q "https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.34/nancy-linux.amd64-v0.0.34" > /usr/bin/nancy\
    && chmod +x /usr/bin/nancy
```
Test: `docker run -it --rm $(docker build -q .) /usr/bin/nancy`

**Comment by zendern** [comment]
Im going to reopen this issue. I have reproduced the above. It does in fact work on 0.0.33 but does fail on 0.0.34. 

https://github.com/sonatype-nexus-community/nancy/compare/v0.0.33...v0.0.34

Looking at the diff between the two nothing sticks out as to what would cause this to start to fail.

**Comment by zendern** [comment]
Found it.... travis requires you to define your env vars on the same line if you want them to affect a single build. Adding them as multiple entries cause travis to spin up multiple builds. 

Build #33
![image](https://user-images.githubusercontent.com/1099906/69203277-e4d90980-0b11-11ea-817c-9990373a79f8.png)

Build #34 
![image](https://user-images.githubusercontent.com/1099906/69203308-f6221600-0b11-11ea-9f7a-f2a1b63287a8.png)

What appears to be happening is that the first build that completes wins as far as what makes it to the release in github. So #33 CGO_ENABLED=0 build won whereas #34 CGO_ENABLED=0 build lost and thus pushed the binary where it was enabled. 

Ill tweak the above PR to fix this so that it only has a single build with CGO_ENABLED=0 set.

**Comment by s-spindler** [comment]
@zendern Alright, thanks a lot for the prompt investigation!
