### ISSUE TITLE
Remove go.sum option

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/nancy#69]
* **What are you trying to do?**
Only support the new authoritative way in go to get a list of dependencies. `go list -m all` should be the way, the path, the truth. So allowing for using `go.sum` should no longer be needed. 

* **What feature or behavior is this required for?**
To not support 2 ways to deal with go mod. `go list -m all` is the authoritative way to do the thing so lets do that.

* **How could we solve this issue? (Not knowing is okay!)**
Remove some code :) 

* **Anything else?**
When we do this its probably a major bump of nancy as we are removing functionality 

cc @bhamail / @DarthHater

**Comment by zendern** [comment]
@DarthHater maybe pull the trigger on removing this in v1.0??

**Comment by SVilgelm** [comment]
Why the go.sum should be removed? Why we cannot use both options?

**Comment by SVilgelm** [comment]
`go list -m all | nancy` works great

**Comment by DarthHater** [comment]
@SVilgelm it's more or less just because `go.sum` files are more like a ledger of what libraries you have used, not what you are currently using. It keeps track of the sha1 of the library, so that if for some reason someone changed a tag upstream etc.... go would be able to tell you, yeah, that's not what you were using before. It provides the mechanism for golang to have `deterministic` builds, but since it can have old versions of libraries in it, it doesn't provide an accurate look at what you are currently using, which is what `go list -m all` does. What we'd be removing is just the ability to scan the `go.sum` file itself, because people could be confused and think they are using something they aren't.

**Comment by SVilgelm** [comment]
but it can really break the current CI scripts. I would recommend to add a deprecation message for a couple of months, then remove

**Comment by DarthHater** [comment]
@SVilgelm this is why we are targeting this for `v1.0.0` and not in the current `v0.x.y` series. It's functionality will stick around for `v0.x.y` releases, which will be mostly patch and no new functionality, but removed from the `v1.0.0` forward, so that people can gradually migrate :)

**Comment by SVilgelm** [comment]
so, it would be great if `nancy` can do it automatically, I mean we don't need to run it like `go list -m all | nancy`

**Comment by bhamail** [comment]
go.sum is gone. Fixed by #161
